-- Author: Evgeny Tomsen
-- repo  : https://github.com/etomsen/dotfiles/

require "etomsen.sql"
require "etomsen.reload"
require "etomsen.daily-note"
require "etomsen.options"
require "etomsen.plugins"
require "etomsen.plugins.terminal"
require "etomsen.plugins.lsp"
require "etomsen.plugins.null-ls"
require "etomsen.plugins.cmp"
require "etomsen.plugins.todo"
require "etomsen.plugins.fzf"
require "etomsen.plugins.treesitter"
require "etomsen.plugins.indent-blankline"
require "etomsen.plugins.nvim-tree"
require "etomsen.plugins.prettier"
require "etomsen.plugins.harpoon"
require "etomsen.plugins.angular"
require "etomsen.telescope"
require "etomsen.mappings"
require "etomsen.colors"
